development:
  adapter: mysql2
  database: message_board
  username: root
  password: matthews

test:
  adapter: mysql2
  database: message_board-test
  username: root
  password: matthews

production:
  adapter: mysql2
  database: message_board
  username: root
  password: matthews
